### ISSUE TITLE
Uninstall / Reinstall not working

### ISSUE THREAD

**Issue by dan-willett** [dwservice/agent#5]
I have a windows 10 machine with DWAgent installed.  It quit working, the icon is no longer showing in the tray, however the service is still running, but the computer is not accessible from my dwservice account.

I tried to uninstall, and it doesn't do anything.  I also tried to run the install again, and it won't install, it says it is already installed.   If it detects that it is already installed, it needs to give the options to re-install or un-install.

**Comment by mikhoul** [comment]
Use "Everything" (https://www.voidtools.com/downloads/) and search for DWAG you will find the folder where there is files that the program detect that prevent you to reinstall DWS.

Just delete those folders/files and try again it should work **BUT** if it did not work it would be because DWS look in the registry  for entry to detect if DWS is installed.

So you would have to download "RegCool" (https://kurtzimmermann.com/regcoolext_en.html) and search again for the string DWS or DWA in your registry and delete those entry and reboot, this way you will be able to reinstall DWS.

Regards :octocat:

**Comment by dan-willett** [comment]
I was able to get it re-installed, but only after removing the registry entries.

**Comment by alokprasad** [comment]
How to i do same in Linux ? 
delete /opt/share/dw.. folder still i cannot to fresh re-install.
as i have to enter code .
